"""
Tests for Toolpath Optimizer: 2-Opt TSP Air Travel Minimizer, G-Code integration, MCP and CLI.
Zero external runtime dependencies.
"""

from __future__ import annotations

import json
from typing import Any, Dict

import pytest

from cyber_turtle_studio.cli import main
from cyber_turtle_studio.exporters.gcode_exporter import GCodeConfig, GCodeExporter
from cyber_turtle_studio.mcp_server import MCPServer
from cyber_turtle_studio.models import DrawingAST, PathSegment, PathSegmentType, Point2D
from cyber_turtle_studio.toolpath_optimizer import (
    Polyline,
    ToolpathOptimizationReport,
    ToolpathOptimizer,
    render_toolpath_comparison_svg,
)
from cyber_turtle_studio.turtle_engine import execute_logo


def test_polyline_extraction_and_reversal() -> None:
    # Segments: (0,0)->(10,0), (10,0)->(10,10), MOVE(20,20), (20,20)->(30,20)
    segs = [
        PathSegment(segment_type=PathSegmentType.LINE, start=Point2D(0, 0), end=Point2D(10, 0)),
        PathSegment(segment_type=PathSegmentType.LINE, start=Point2D(10, 0), end=Point2D(10, 10)),
        PathSegment(segment_type=PathSegmentType.MOVE, start=Point2D(20, 20), end=Point2D(20, 20)),
        PathSegment(segment_type=PathSegmentType.LINE, start=Point2D(20, 20), end=Point2D(30, 20)),
    ]
    ast = DrawingAST(title="test", segments=segs)

    optimizer = ToolpathOptimizer()
    polylines = optimizer.extract_polylines(ast)

    assert len(polylines) == 2
    assert len(polylines[0].segments) == 2
    assert len(polylines[1].segments) == 1
    assert polylines[0].length == 20.0

    # Test reversal
    rev = polylines[0].reversed()
    assert rev.start_point == Point2D(10, 10)
    assert rev.end_point == Point2D(0, 0)
    assert rev.length == 20.0


def test_toolpath_optimization_reduction() -> None:
    # Build worst-case disconnected ladder: lines drawn with alternating far hops
    # Line 0: (0, 0) -> (10, 0)
    # Line 1: (0, 80) -> (10, 80)
    # Line 2: (0, 20) -> (10, 20)
    # Line 3: (0, 100) -> (10, 100)
    # Line 4: (0, 40) -> (10, 40)
    y_coords = [0, 80, 20, 100, 40]
    segs = []
    for y in y_coords:
        segs.append(PathSegment(segment_type=PathSegmentType.MOVE, start=Point2D(0, y), end=Point2D(0, y)))
        segs.append(PathSegment(segment_type=PathSegmentType.LINE, start=Point2D(0, y), end=Point2D(10, y)))

    ast = DrawingAST(title="scrambled_ladder", segments=segs)
    optimizer = ToolpathOptimizer()
    opt_ast, report = optimizer.optimize_toolpath(ast)

    assert report.total_polylines == 5
    assert report.drawing_distance_mm == 50.0
    assert report.optimized_air_travel_mm < report.initial_air_travel_mm
    assert report.reduction_percent > 20.0
    assert report.efficiency_score > 0.0


def test_render_toolpath_comparison_svg() -> None:
    ast = execute_logo("REPEAT 4 [ FD 50 PU HOME RT 90 PD ]")
    optimizer = ToolpathOptimizer()
    opt_ast, report = optimizer.optimize_toolpath(ast)

    svg_str = render_toolpath_comparison_svg(ast, opt_ast)
    assert svg_str.startswith("<svg")
    assert "</svg>" in svg_str
    assert "Unoptimized Toolpath" in svg_str
    assert "2-Opt Optimized Toolpath" in svg_str


def test_gcode_config_optimize_paths() -> None:
    ast = execute_logo("REPEAT 4 [ FD 40 PU RT 90 FD 20 PD ]")
    cfg = GCodeConfig(optimize_paths=True, home_on_start=False)
    exporter = GCodeExporter(config=cfg)
    gcode, stats = exporter.generate(ast)

    assert "G-Code generated by cyber-turtle-studio" in gcode
    assert "G1" in gcode
    assert stats["total_lines"] > 0


def test_mcp_tool_optimize_toolpath() -> None:
    server = MCPServer()
    res = server.handle_tool_call(
        "turtle_optimize_toolpath",
        {"script": "REPEAT 4 [ FD 30 PU HOME RT 90 PD ]", "include_comparison_svg": True}
    )
    assert "content" in res
    data = json.loads(res["content"][0]["text"])
    assert "drawing_distance_mm" in data
    assert "comparison_svg" in data
    assert data["total_polylines"] > 0


def test_cli_optimize_command(capsys: pytest.CaptureFixture[str], tmp_path) -> None:
    # Test CLI with --json
    code = main(["optimize", "-s", "REPEAT 4 [ FD 30 PU HOME RT 90 PD ]", "--json"])
    assert code == 0
    out = capsys.readouterr().out
    data = json.loads(out)
    assert "reduction_percent" in data

    # Test CLI with --svg
    out_svg = str(tmp_path / "comparison.svg")
    code_svg = main(["optimize", "-s", "REPEAT 4 [ FD 30 PU HOME RT 90 PD ]", "--svg", out_svg])
    assert code_svg == 0
    out_msg = capsys.readouterr().out
    assert "Pen-Plotter Toolpath Optimization Report" in out_msg
